---
title: "Virtual Reality Interventions: Evaluating Efficacy in the Treatment of GAD"
author: "Alan Kinsela, Erik Trujillo"
date: "13/02/2023"
output: html_document
---

# Setup 
```{r include=FALSE}
if(!require("knitr"))
library(knitr)

# Load the packages, loading tidyverse for readr, dplyr, magrittr, and ggplot2
if(!require("tidyverse"))
library(tidyverse)
```



```{r} 
#Setting this up to define all chunks to show both code and output: https://argoshare.is.ed.ac.uk/healthyr_book/the-anatomy-of-a-notebook-r-markdown-file.html
knitr::opts_chunk$set(echo = TRUE)

```


<!-- This is what a comment looks like-->
### Table of Contents

1. [Abstract](#abstract)
2. [Introduction](#introduction)
3. [Method](#method)
4. [Results](#results)
5. [Discussion](#discussion)
6. [References](#references)


### Abstract <a name="abstract"></a>



### Introduction <a name="introduction"></a>
```{r echo=FALSE}
print(RESULTS_CONTROL)
```

```{r echo=FALSE}
print(RESULTS_EXPERIMENTAL)
```



### Method <a name="method"></a>




### Results <a name="results"></a>




### Discussion <a name="discussion"></a>




### References <a name="references"></a>